import Head from "next/head";
import { useRouter } from "next/router";

export default function Footer() {

  const router = useRouter();
  return (
    <>
      <Head>
        <title>Settings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div class="inline-flex justify-evenly fixed bottom-0 items-center w-full h-16
         bg-white border-t border-gray-200 dark:bg-gray-700
         dark:border-gray-600 text-white">
          <div class="flex-col items-center justify-center"  onClick={() => router.push("/")}>
          
            <p>Home</p>
          </div>

          <div onClick={() => router.push("/explore")}>
          

          <p>Explore</p>
          </div>

          <div  onClick={() => router.push("/messages")}>
          

          <p>Messages</p>
          </div>

          <div  onClick={() => router.push("/settings")}>
          

          <p>Settings</p>
          </div>
        </div>
      </main>
    </>
  );
}



