import Footer from "@/components/Footer";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Settings() {

  const router = useRouter();
  return (
    <>
      <Head>
        <title>Settings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
<h1>Settings Page</h1>
<Footer />
      </main>
    </>
  );
}